import Head from 'next/head';
import styles from '../styles/Home.module.css';

import SignInUp from '../components/SignInUp';
import PrimarySearchAppBar from '../components/PrimarySearchAppBar';
import MainLayout from '../components/MainLayout'; 

export default function Home() {

  return (
    <div className={styles.container}> 
      <Head> 
        <title>Harry Potter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/harry-potter" rel="stylesheet"/>         
      </Head>

      <main className={styles.main}>
        <SignInUp/>
        {/* <PrimarySearchAppBar/> */}
        {/* <MainLayout/> */}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
